### PR TITLE
Switch from lazy_static to once_cell

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
That was the last one.

**Comment by sdroege** [comment]
This can probably be retried and merged now?

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by sdroege** [comment]
@GuillaumeGomez What's all the noise with the docs about in here? :)

**Comment by GuillaumeGomez** [comment]
You need to update `.travis.yml` minimum rust version to 1.39. :)

**Comment by sdroege** [comment]
Not sure how that's related to the docs, but yes that's a good idea regardless :)

**Comment by sdroege** [comment]
@GuillaumeGomez green :)

**Comment by GuillaumeGomez** [comment]
That at least explains why I didn't see the connection with the docs in this error haha. What's the problem with the docs then?

(and thanks! merging)

**Pull request merged**
